job_search_db = {
job_offers:[
    "id",
    "category",
    "tech_stack",
    "comment",
    "status",
    "sent_date",
    "response_date",
    "link",
    "title",
    "location",
    "location_type",
    "salary",
    "salary_type",
    "years_of_experience",
    "company",
    "company_link",
    "company_description",
    "responsibilities",
    "requirements",
    "benefits",
    "body",
    "full_offer",
    "date_of_access"
    # ("id", int),
    # ("category", ["Data", "Mobile", "QA", "Security", "UX/UI", "Ruby", "Manager", "DevOps", "Backend", "Frontend", "Fullstack", "AI", "Support"]), 
    # ("tech_stack", string),
    # ("comment", string),
    # ("status", string),
    # ("sent_date", DATE),
    # ("response_date", DATE),
    # ("link", string),
    # ("title", string),
    # ("location", string),
    # ("location_type", string),
    # ("salary", string),
    # ("salary_type", string),
    # ("years_of_experience", TEXT),
    # ("company", VARCHAR(255)),
    # ("company_link", VARCHAR(255)),
    # ("company_description", TEXT),
    # ("responsibilities", TEXT),
    # ("requirements", TEXT),
    # ("benefits", TEXT),
    # ("body", TEXT),
    # ("full_offer", TEXT),
    # ("date_of_access", DATE)
]
}